In [1]:
# calculate
# comment 1
# comment 2

# Heading 1
## Heading 2

*coursive*

**bold text**

* point 1
* point 1

1. point 1
2. point 2
4. point 3

a. point 1
b. point 2

[Jupyter](https://jupyter.org/)

<https://jupyter.org/>

$$
y_i = \beta_0 + \beta_1 \cdot x_i
$$

In [4]:
a = int(7/3)
print(a)
print(type(a))

2
<class 'int'>


In [26]:
3 // 2

1

In [31]:
9 ** 2 + 6 ** 4

1377

In [58]:
from math import log
log(54)

3.9889840465642745

In [57]:
from math import sqrt
sqrt(8) - sqrt(12)

-0.6356744903915641

In [59]:
from math import sin, cos
math.sin(45) + math.cos(45)

1.3762255133518482

In [34]:
size = int(input())
print(size-2)

f


ValueError: invalid literal for int() with base 10: 'f'

In [11]:
part1 = int(input())
part2 = int(input())
part3 = int(input())
print(part1 + part3 + part3)

1
2
3
7


In [60]:
salary = 35000
salary_th = salary // 1000
print(salary_th)
print('Ваша заработная плата', salary_th, 'тысяч рублей.')

35
Ваша заработная плата 35 тысяч рублей.


In [46]:
money = int(input())
print(money + money / 20)

1000
1050.0


In [76]:
a = int(input())
print((a // 2) * 2 + 2)

11
12


In [70]:
pers1 = '5'
pers2 = input()
pers3 = input()
pers4 = input()
summ = int(pers1 + pers2 + pers3 + pers4)
print(summ, type(summ))

1
2
3
5123 <class 'int'>


from decimal import Decimal

In [66]:
Decimal(3.52567)

Decimal('3.5256699999999998595967554138042032718658447265625')

In [71]:
from math import sin, cos

In [72]:
sin(45) + cos(45)

1.3762255133518482

In [1]:
.435763287623486520345760238650234865238504

0.43576328762348654

In [2]:
.3 + .3 + .3 + .1

0.9999999999999999

In [12]:
from decimal import Decimal
Decimal(.3)

Decimal('0.299999999999999988897769753748434595763683319091796875')

In [5]:
100 ** .5

10.0

In [6]:
'''qwerty
qwert
qwer'''

'qwerty\nqwert\nqwer'

In [9]:
Decimal('1')

Decimal('1')

In [10]:
'ಹಲೋ'

'ಹಲೋ'

In [14]:
'привет'.encode()

b'\xd0\xbf\xd1\x80\xd0\xb8\xd0\xb2\xd0\xb5\xd1\x82'

In [9]:
'helpa'[:0]

''

In [10]:
'0123456789'[9:0:-2]

'97531'

In [14]:
vlave = 42

In [15]:
mass = 0

In [16]:
mass = vlave

In [8]:
mass += 1

In [9]:
print(vlave, mass)

42 85


In [22]:
id(vlave)

140707712964704

In [23]:
id(mass)

140707712964704

In [25]:
mass += 1

In [26]:
id(mass)

140707712964768

In [28]:
my_box = {}

In [29]:
my_box['Розовый'] = 'Слон'

In [30]:
my_box

{'Розовый': 'Слон'}

In [31]:
my_box['Рыжий'] = 'Котик'

In [34]:
my_box

{'Розовый': 'Слон', 'Рыжий': 'Котик'}

In [35]:
my_box['Розовый']

'Слон'

In [36]:
my_box['Слон']

KeyError: 'Слон'

In [37]:
my_box.get('Синий', 'Машинка')

'Машинка'

In [39]:
my_box.setdefault('Розовый', 'Машинка')

'Слон'

In [40]:
my_box

{'Розовый': 'Слон', 'Рыжий': 'Котик', 'Синий': 'Машинка'}

In [17]:
seconds = int(input('Введите количество секунд: '))
days = seconds // 86400
seconds = seconds - days * 86400
hours = seconds // 3600
seconds = seconds - hours * 3600
first_minutes = seconds // 600
seconds = seconds - first_minutes * 600
second_minutes = seconds // 60
seconds = seconds - second_minutes * 60
first_seconds = seconds // 10
seconds = seconds % 10
print(hours, ':', first_minutes, second_minutes, ':', first_seconds, seconds, sep = '')

Введите количество секунд: 86399
23:59:59


In [14]:
3600 * 24

86400

In [25]:
v = int(input('Введите скорость движения машины: '))
t = int(input('Введите время движения машины: '))
s = v * t
direct_km = s % 109
print(direct_km)

Введите скорость движения машины: 2072
Введите время движения машины: 1
1


In [24]:
109*19+1

2072

In [30]:
number = int(input('Введите пятизначное число: '))
first_number = number // 10000
number = number - first_number * 10000
second_number = number // 1000
number = number - second_number * 1000
third_number = number // 100 
number = number - third_number * 100
fours_number = number // 10
number = number % 10
print(first_number + second_number + third_number + fours_number + number)

Введите пятизначное число: 11111
5


In [ ]:
numbers = input().split(sep=',')
numbers = list(map(int, numbers))
max_value = numbers[0]
for number in numbers:
    if number > max_value:
        max_value = number
print(max_value)

In [26]:
number = int(input('Введите число: '))
numbers_list = list()
numbers_list.append(number)
max_value = number

while number != 0:
    number = int(input('Введите число: '))
    if number in numbers_list:
        continue
    numbers_list.append(number)
    
for number in numbers_list:
    if number > max_value:
        max_value = number

for number in numbers_list:
    if number == max_value:
        numbers_list.remove(number)

max_value = numbers_list[0]

for number in numbers_list:
    if number > max_value:
        max_value = number
        
print('Второе по величине число:', max_value)

Введите число: 11
Введите число: 11
Введите число: 11
Введите число: 11
Введите число: 11
Введите число: 10
Введите число: 9
Введите число: 0
Второе по величине число: 10


In [58]:
year = int(input('Введите год: '))
if year % 400 == 0:
    print('В этом году 366 дней')
elif year % 4 == 0 and year % 100 != 0:
    print('В этом году 366 дней')
else:
    print('В этом году 365 дней')

Введите год: 400
В этом году 366 дней


In [124]:
number = int(input('Введите число: '))
if number == 2:
    print('Число простое')
else:
    devider = number - 1
    deviders_list = list()
    deviders_list.append(devider)

    while devider > 2:
        devider -= 1
        deviders_list.append(devider)
    
    for i in deviders_list:
        if number % i == 0:
            output = 'Число составное'
            break
        else:
            output = 'Число простое'
    print(output)

Введите число: 59
Число простое


In [143]:
number = int(input('Введите число: '))
devider = 1
deviders_list = list()

while devider < number:
    devider += 1
    deviders_list.append(devider)
    
    for i in deviders_list:
        if number % i == 0:
            output = i
            break

print('Наименьший натуральный делитель числа', number, 'это', output)

Введите число: 1
Наименьший натуральный делитель числа 1 это 2


In [3]:
marathon_distance = int(input('Введите дистанцию марафона в киллометрах: '))
first_run = int(input('Ввидите результат первого забега в киллометрах: '))
percents = int(input('Введите количество процентов, на которое будет увеличиваться результат: '))
days = 0
one_run = first_run
final_percents = percents

while marathon_distance > one_run:
    one_run = first_run * final_percents / 100
    final_percents += percents
    days += 1
print(days)

Введите дистанцию марафона в киллометрах: 1
Ввидите результат первого забега в киллометрах: 1
Введите количество процентов, на которое будет увеличиваться результат: 100
0


In [22]:
n = int(input('Введите число: '))
i = 0
numbers_less_n = list()
summ_of_squares = 0

while i < n:
    i += 1
    numbers_less_n.append(i)
    
for number in numbers_less_n:
    summ_of_squares += number ** 2
print('Искомая сумма равна:', summ_of_squares)

Введите число: 1
Искомая сумма равна: 1


In [26]:
n = int(input('Введите число: '))
i = 0
numbers_less_n = list()
factorial = 1
summ_of_factorials = 0

while i < n:
    i += 1
    numbers_less_n.append(i)
    
for number in numbers_less_n:
    factorial = factorial * number
    print(factorial)
    summ_of_factorials += factorial
    
print('Искомая сумма равна:', summ_of_factorials)

Введите число: 7
1
2
6
24
120
720
5040
Искомая сумма равна: 5913


In [8]:
number = int(input('Введите число: '))
parity = 0
if number % 2 == 0:
    parity += 1

while number != 0:
    number = int(input('Введите число: '))
    if number % 2 == 0:
        parity += 1
    
print('Второе по величине число:', parity)

Введите число: 1
Введите число: 2
Введите число: 3
Введите число: 4
Введите число: 5
Введите число: 6
Введите число: 7
Введите число: 8
Введите число: 9
Введите число: 0
Второе по величине число: 5


In [20]:
sex = input('Введите пол: ')
if sex.lower() == 'женский':
    age = int(input('Введите ваш возраст: '))
    if 18 <= age <= 35:
        print('Вы подходите!')
    else:
        print('Вы не подходите по возрасту!')
else:
    print('В женскую лигу можно только представительницам женского пола')

Введите пол: мужской
В женскую лигу можно только представительницам женского пола


In [49]:
rhombus_width = int(input('Введите ширину ромба: '))
check = rhombus_width
stars = 1
while rhombus_width > 0:
    print(rhombus_width // 2 * ' ', stars * '*', rhombus_width // 2 * ' ')
    stars += 2
    rhombus_width += (-2)
stars += (-2)
rhombus_width += 2
while rhombus_width < check:
    stars += (-2)
    rhombus_width += 2
    print(rhombus_width // 2 * ' ', stars * '*', rhombus_width // 2 * ' ')

Введите ширину ромба: 17
         *         
        ***        
       *****       
      *******      
     *********     
    ***********    
   *************   
  ***************  
 ***************** 
  ***************  
   *************   
    ***********    
     *********     
      *******      
       *****       
        ***        
         *         


In [55]:
x_width = int(input('Введите ширину ромба: ')) - 2
check = x_width
while x_width > 0:
    spaces = x_width - 2
    x_width += (-2)
    print('X', spaces * ' ', 'X', sep='')

Введите ширину ромба: 5
X X
XX


In [1]:
5 + 10 + 15

30

In [2]:
5 + (5+5) + (5+5+5)

30

In [9]:
5 + 10 + 15 + 20 + 25 + 30 + 35 + 40

180

In [6]:
40 % 60

40

In [97]:
num = int(input("Введите число: "))
first_num = num
second_num = num

while True:
  num = int(input("Введите число: "))
  if num == 0:
    break
  if (second_num == first_num) and (num < first_num):
    second_num = num
  elif num > first_num:
    second_num = first_num
    first_num = num
  elif second_num < num < first_num:
    second_num = num

print(second_num)

Введите число: 121
Введите число: 2432
Введите число: 4232
Введите число: 0
2432


In [1]:
def print_them_all_v2(**kwargs):
    print('Тип kwargs', type(kwargs))
    print(kwargs)
    for key, value in kwargs.items():
        print('Именованый аргумент:', key, '=', value)
        
print_them_all_v2(name='Вася', adress='Moscow', age='42')

Тип kwargs <class 'dict'>
{'name': 'Вася', 'adress': 'Moscow', 'age': '42'}
Именованый аргумент: name = Вася
Именованый аргумент: adress = Moscow
Именованый аргумент: age = 42


In [9]:
def print_them_all_final(a, b=4, *args, **kwargs):
    print('print_them_all_final')
    print('a и b:', a, b)
    print('тип args:', type(args))
    print(args)
    for i, arg in enumerate(args):
        print('Позиционный параметр:', i, arg)
    print('тип kwargs:', type(kwargs))
    print(kwargs)
    for key, value in kwargs.items():
        print('Именованный аргумент:', key, '=', value)

        
pos = (5, 6, 7, 8)
names = {'cat': 'nyan', 'adress': 'Tokio'}
print_them_all_final(5, *pos, **names)    

print_them_all_final
a и b: 5 5
тип args: <class 'tuple'>
(6, 7, 8)
Позиционный параметр: 0 6
Позиционный параметр: 1 7
Позиционный параметр: 2 8
тип kwargs: <class 'dict'>
{'cat': 'nyan', 'adress': 'Tokio'}
Именованный аргумент: cat = nyan
Именованный аргумент: adress = Tokio


In [42]:
def exponente_v2(n, m):
    if m == -1:
        return 1 / n
    exponente_v2_minus_1 = exponente_v2(n, m=m+1)
    return 1 / n * exponente_v2_minus_1

print(exponente_v2(3, -1))

0.3333333333333333


In [43]:
3 ** (-1)

0.3333333333333333

In [3]:
html_dom = {
    'html' : {
        'head' : {
            'title' : 'Колобок'
        },
        'body' : {
            'h2' : 'Привет!',
            'div' : 'Хочешь расскажу тебе сказку?',
            'p' : 'Жили были дед и бабка...'
        }
    }
}


def find_element(tree, element_name):
    if element_name in tree:
        return tree[element_name]
    for key, sub_tree in tree.items():
        if isinstance(sub_tree, dict):
            result = find_element(tree=sub_tree, element_name=element_name)
            if result:
                break
    else:
        result = None
    return result

res = find_element(tree=html_dom, element_name='title')
print(res)

Колобок


In [45]:
S = 0
def sum(n, m):
    S = n + m
    return S

print(sum(3, 4))
print(S)

7
0


In [1]:
bool(-1)

True

In [18]:
#Операции со списками

profit = (200, 300, 500, 100, 1800)
days = ('пн', 'вт', 'ср', 'чт', 'пт', 'сб')

print(profit)
print(len(profit))
print(max(profit))
print(min(profit))
print(sorted(profit))
print(sum(profit))
print(profit)

res = zip(days, profit)
print(dict(res))

(200, 300, 500, 100, 1800)
5
1800
100
[100, 200, 300, 500, 1800]
2900
(200, 300, 500, 100, 1800)
{'пн': 200, 'вт': 300, 'ср': 500, 'чт': 100, 'пт': 1800}


In [10]:
a = 2
b = 4
def reduction(a, b):
    for i in range(1, min(a, b)+1):
        if a % i == 0 and b % i == 0:
            a = a / i
            b = b / i
    return a, b
    
print(reduction(a, b))

(1.0, 2.0)


In [26]:
# Родительский класс
 
class A(object):
 
    def __init__(self):
        print(u'конструктор класса A')
 
# Потомок класса А
class B(A):
 
    def __init__(self):
        print(u'конструктор класса B')
        super(B,self).__init__()
        
a = B()
print(a)

конструктор класса B
конструктор класса A


In [1]:
import numpy as np

In [2]:
np.sqrt(17)

4.123105625617661

In [3]:
np.log(4)

1.3862943611198906

In [7]:
np.mean([20, 40, 30, 450, 45, 30])

102.5

In [8]:
np.median([20, 40, 30, 450, 45, 30])

35.0

In [10]:
np.array([2, 3, 4])

array([2, 3, 4])

In [12]:
np.array([[5, 2, 3.5],
          [1, 9, 6.5]])

array([[5. , 2. , 3.5],
       [1. , 9. , 6.5]])

In [15]:
np.array([[[6, 3],
           [6, 8]], 
          [[1, 0],
           [0, 1]]])
    

array([[[6, 3],
        [6, 8]],

       [[1, 0],
        [0, 1]]])

In [18]:
turnout = np.array([0.62, 0.43, 0.79, 0.56])
turnout * 100

array([62., 43., 79., 56.])

In [111]:
i = 0
x = 0
a = [int(i) for i in input().split()]
for j in range(len(a)):
    if len(a) == 1:
        print(a[0])
    elif j == len(a)-1:
        x = a[0] + a[j-1]
        print(x, end=' ')
    else:
        x = a[j-1] + a[j+1]
        print(x, end=' ')

1 2 3 3 3 3
5 4 5 6 6 4 

In [95]:
text = input()+' '
letter = text[0]
count = 0
for i in text:
    if i != letter:
        print(letter + str(count), end='')
        count = 1
        letter = i
    else:
        count += 1

dffdddffff
d1f2d3f4

In [69]:
'd' == 'd'

True

In [38]:
s = str(input())
l = len(s)-1
c = 1
t = ''
if len(s)==1:
    t = t +s+str(c)
else:
    for i in range(0,l):
        if s[i]==s[i+1]:
            c +=1
        elif s[i]!=s[i+1]:
            t = t + s[i]+str(c)
            c = 1
    for j in range(l,l+1):
        if s[-1]==s[-2]:
            t = t +s[j]+str(c)
        elif s[-1]!=s[-2]:
            t = t +s[j]+str(c)
            c = 1
print(t)

ffffddddfffd
f4d4f3d1


In [174]:
numbers = [int(i) for i in input().split(' ')]
numbers.sort()
final = []
for i in range(len(numbers)):
    if len(numbers) == 1: 
        final = [] # при подаче одного элемента не выдает его же в результате
    elif numbers[i] == numbers[i-1]:
        if numbers[i] not in final:
            final.append(numbers[i])
# if len(final) == 0:
#     print(' ')
# else:
#     for i in final:
#         print(i, end=' ')
# этот кусок вставляем если нужен возврат ' ' при отсутствии повторений

for i in final:
    print(i, end=' ') # если не нужен возврат ' ' при отсутствии повторений

10


In [175]:
print(int(-10))

-10


In [185]:
num = int(input())
summ = num
sqrt_summ = summ**2
while summ != 0:
    num = int(input())
    summ += num
    sqrt_summ += num**2
print(sqrt_summ)

2
-2
8


In [16]:
lst = [int(i) for i in input().split(' ')]
x = int(input())
funn = ''
if x not in lst:
    print("Отсутствует")
else:
    for j in range(len(lst)):
        if lst[j] == x:
            print(str(j), end=' ')

1 1 1
1
0 1 2 

In [ ]:
lst = input()
matrx = [lst]
while lst != 'end':
    lst = input()
    lst = lst.split(' ')
    matrx.append(lst)
print(matrx)

1 2 3
1 2 3
1 2 3
end


In [7]:
l = [[2, 5, 0], [7, 8, 1]]
r = [[l[j][i] for j in range(len(l))] for i in range(len(l[0]))]
print(*(i for i in r), sep='\n')

[2, 7]
[5, 8]
[0, 1]


In [4]:
import numpy as np
A = np.array([[2, 9, 8, 0],
             [8, 7, 5, 6], 
             [3, 1, 0, 2], 
             [6, 5, 6, 8],
             [1, 0, 0, 4]])

In [24]:
res = [[A[j][i] for j in range(len(A))] for i in range (len(A[0]))]
np.array(res)

array([[2, 8, 3, 6, 1],
       [9, 7, 1, 5, 0],
       [8, 5, 0, 6, 0],
       [0, 6, 2, 8, 4]])

In [8]:
def f(x):
    if x <= -2:
        x = 1 - (x + 2)**2
    elif -2 < x <= 2:
        x = -x/2
    elif 2 < x:
        x = (x - 2)**2 + 1
    return x

for i in range(-3, 3):
    print(f(i))

0
1
0.5
0.0
-0.5
-1.0


In [52]:
l = [3, 4, 5, 6]
def modify_list(l):
    t = []
    for i in (l, 1, -1):
        if i % 2 != 0:
            l.remove(i)
    for i in l:
        t.append(int(i/2))
    return(t)

print(modify_list(l))

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [136]:
import numpy as np
def build_array(n):
    f = np.zeros((n, n))
    for i in range(n):
        f[i][i] = 1.
    return f

build_array(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
arr = np.load('array_hw.npy')

In [66]:
arr

array([[100,  80,  70,  60, 120],
       [ 65,  55,  20,  50,  60],
       [ 80,  90,  75,  80,  60],
       [ 45,  60,  70,  20,  40],
       [ 82,  47,  56,  89,  92],
       [115, 120, 113, 106, 107],
       [ 46,  74,  23,  34,  19]], dtype=int64)

In [67]:
arr.T

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  55,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  19]], dtype=int64)

In [69]:
arr = arr.T

In [70]:
arr

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  55,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  19]], dtype=int64)

In [73]:
arr[4][6] = 25
arr[1][1] = 65

In [74]:
arr

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  65,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  25]], dtype=int64)

In [75]:
np.sum(arr)

2439

In [76]:
income = np.array([1000, 2000, 3500, 
                   2500, 1500, 3800, 
                   1200, 9000, 12000,
                   4500, 6700, 11000])

In [81]:
income = income.reshape(4, 3)

In [82]:
income

array([[ 1000,  2000,  3500],
       [ 2500,  1500,  3800],
       [ 1200,  9000, 12000],
       [ 4500,  6700, 11000]])

In [122]:
turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
type(turnout)

list

In [123]:
turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
for i in range(len(turnout)):
    turnout[i] = round(turnout[i], 1)
turnout

[23.6, 45.8, 34.9, 57.3, 56.5, 67.2]

In [126]:
turnout = np.array([23.56, 45.78, 34.92, 57.34, 56.55, 67.23])
np.around(turnout, 1)

array([23.6, 45.8, 34.9, 57.3, 56.6, 67.2])

In [138]:
happy = np.array([('Бангладеш', 5.0, 68.9, 0.7), ('Молдавия', 5.6, 69.3, 2.1), ('Государство Палестина', 4.8, 72.8, 1.4), 
                  ('Албания', 5.3, 76.9, 1.8), ('Гондурас', 5.9, 73.1, 1.7)], 
                 dtype=[('Название страны', 'U25'), ('Удовлетворенность жизнью', float), 
                        ('Ожидаемая продолжительность жизни', float), ('Эколон=гический след', float)])
print(happy)

[('Бангладеш', 5. , 68.9, 0.7) ('Молдавия', 5.6, 69.3, 2.1)
 ('Государство Палестина', 4.8, 72.8, 1.4) ('Албания', 5.3, 76.9, 1.8)
 ('Гондурас', 5.9, 73.1, 1.7)]


In [140]:
happy.tolist()[1]

('Молдавия', 5.6, 69.3, 2.1)

In [49]:
import numpy as np
def my_reshape(a, l, k):
    f = a.ravel().tolist()
    if l * k == len(f):
        a = np.array([[None for j in range(k)] for i in range(l)])
        t = 0
        for i in range(l):
            for j in range(k):
                a[i][j] = f[t]
                t += 1
        return a
    else:
        return np.array([])

A = np.array([[2, 4, 6], 
        [4, 8, 10]])

my_reshape(A, 4, 2)

array([], dtype=float64)